### ISSUE TITLE
Add Product Detail page, including functionality for button to add to cart (addresses #7)

### ISSUE THREAD

**Issue by jess010** [FullstackTrio/GraceShopper#73]

**Comment by sjhelba** [comment]
are 7 and 73  the same issue?

**Comment by jess010** [comment]
Yes. I thought there was value in having both a specific task, as well as the original requirement so I left them both and noted the link.

**Comment by sjhelba** [comment]
Oh, how do I tell what's been linked?
-------- Original message --------From: jess010 <notifications@github.com> Date: 9/17/17  7:18 PM  (GMT-05:00) To: FullstackTrio/GraceShopper <GraceShopper@noreply.github.com> Cc: Sara Helba <sjhelba@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [FullstackTrio/GraceShopper] Add Product Detail page, including
  functionality for button to add to cart (addresses #7) (#73) 
Yes. I thought there was value in having both a specific task, as well as the original requirement so I left them both and noted the link.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FullstackTrio/GraceShopper","title":"FullstackTrio/GraceShopper","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/FullstackTrio/GraceShopper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jess010 in #73: Yes. I thought there was value in having both a specific task, as well as the original requirement so I left them both and noted the link."}],"action":{"name":"View Issue","url":"https://github.com/FullstackTrio/GraceShopper/issues/73#issuecomment-330101064"}}}

**Comment by jess010** [comment]
I'm just using the reference in the waffle ticket as the link, not sure if there's another way to bundle these.

When closing 'linked' issues though, should reference both, e.g. "closes #1000 and #1001"
